export default {
  LOGIN: 'login',
  REGISTER: 'register',
  HOME: 'home',
  PROFILE: 'profile',
  NOTIFICATION: 'notification',
  TAB: 'tab',
  REGISTER_BUYER: 'registerBuyer',
  VENDOR: 'vendor',
  CART: 'cart',
  AUTH_PHONE: 'authPhone',
  CHECKOUT: 'checkout',
  NEAR_VENDOR: 'nearVendor',
  LIST_ORDERS: 'listOrders',
}