export default {
  LOGIN: 'login',
  REGISTER: 'register',
  HOME: 'home',
  PROFILE: 'profile',
  NOTIFICATION: 'notification',
  TAB: 'tab',
  REGISTER_BUYER: 'registerBuyer',
  VENDOR: 'vendor',
  CART: 'cart',
  AUTH_PHONE: 'authPhone',
  CHECKOUT: 'checkout',
  NEAR_VENDOR: 'nearVendor',
  LIST_ORDERS: 'listOrders',
  TRACK_ORDER: 'trackOrder',
  ORDER_DETAIL: 'orderDetail',
  REVIEW_SHIPPER: 'reviewShipper',
  REVIEW_VENDOR: 'reviewVendor',
  REVIEW_ORDER: 'reviewOrder',
  WALLET: 'wallet',
  FAVORITE: 'favorite',
  FORGOT_PASSWORD: 'forgotPassword',
  CHECK_CODE: 'checkCode',
  UPDATE_PASSWORD: 'updatePassword',
  PROMOTION_VENDOR: 'promotionVendor',
}